config/routes.rb
Rails.application.routes.draw do
  resources :reservations
  resources :profiles
  get 'listings/create'

  get 'listings/new'

  get 'listings/show'

  get 'listings/index'

  get 'listings/update'

  get 'listings/edit'

  get 'listings/destroy'

  get 'search', to: 'search#search'

  resources :passwords, controller: "clearance/passwords", only: [:create, :new]
  resource :session, controller: "clearance/sessions", only: [:create]

  resources :users, controller: "clearance/users", only: [:create] do
    resource :password,
      controller: "clearance/passwords",
      only: [:create, :edit, :update]
  end

  resources :users, only: [:show, :edit, :update, :destroy] 

  resources :listings 

  resources :transactions, only: [:new, :create]

  resources :users, only:[:create, :new, :show, :edit, :update, :destroy, :index] do
    resources :listings
  end

  resources :users, only:[:create, :new, :show, :edit, :update, :destroy, :index] do
    resources :reservations
  end

   resources :users, only:[:create, :new, :show, :edit, :update, :destroy] do
    resources :profile, except:[:index]
  end

  get "/sign_in" => "clearance/sessions#new", as: "sign_in"
  delete "/sign_out" => "clearance/sessions#destroy", as: "sign_out"
  get "/sign_up" => "clearance/users#new", as: "sign_up"
  get "/auth/:provider/callback" => "sessions#create_from_omniauth"

  root 'users#index'

end

app/models/profile.rb
class Profile < ActiveRecord::Base
	belongs_to :user
	validates_presence_of :name, :location, :profile_pic

	validates_uniqueness_of :user_id
	mount_uploader :profile_pic, ImageUploader
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :set_profile, only: [:show, :edit, :update, :destroy]
  before_action :require_login

  # GET /profiles
  # GET /profiles.json
  def index
    @profiles = Profile.all
  end

  # GET /profiles/1
  # GET /profiles/1.json
  def show
  end

  # GET /profiles/new
  def new
    @profile = Profile.new
  end

  # GET /profiles/1/edit
  def edit
  end

  # POST /profiles
  # POST /profiles.json
  def create
    @profile = Profile.new(profile_params.merge(user_id: current_user.id))
    # @profile = Profile.new(profile_params)

    respond_to do |format|
      if @profile.save
        format.html { redirect_to @profile, notice: 'Profile was successfully created.' }
        format.json { render :show, status: :created, location: @profile }
      else
        format.html { render :new }
        format.json { render json: @profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /profiles/1
  # PATCH/PUT /profiles/1.json
  def update
    respond_to do |format|
      if @profile.update(profile_params)
        format.html { redirect_to @profile, notice: 'Profile was successfully updated.' }
        format.json { render :show, status: :ok, location: @profile }
      else
        format.html { render :edit }
        format.json { render json: @profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /profiles/1
  # DELETE /profiles/1.json
  def destroy
    @profile.destroy
    respond_to do |format|
      format.html { redirect_to profiles_url, notice: 'Profile was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_profile
      @profile = Profile.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def profile_params
      # params[:profile][:user_id] = current_user.id
      params.require(:profile).permit(:name, :location, :profile_pic, :user_id)
    end
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/views/profiles/_form.html.erb
<%= form_for(@profile) do |f| %>
  <% if @profile.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@profile.errors.count, "error") %> prohibited this profile from being saved:</h2>

      <ul>
      <% @profile.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :location %><br>
    <%= f.text_field :location %>
  </div>
  <div class="field">
    <%= f.label :profile_pic %><br>
    <%= f.file_field :profile_pic %>
  </div>
  <br>
  <div class="actions">
    <%= f.submit "Submit Profile", class: "btn btn-success" %>
  </div>
<% end %>

app/views/profiles/edit.html.erb
<h1>Edit Your Profile</h1>

<%= render 'form' %>

<div class="pull-right" style="margin-right: 2%">
<%= link_to 'Show', @profile, class: "btn btn-warning" %> |
<%= link_to 'Back', profiles_path, class: "btn btn-primary" %>
</div>
<br>
<br>
<br>
<br>

app/views/profiles/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Profiles</h1>

<table width="100%">
  <thead>
    <tr>
      <th>Name</th>
      <th>Location</th>
      <th>Profile pic</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @profiles.each do |profile| %>
      <tr>
        <td><%= profile.name %></td>
        <td><%= profile.location %></td>
        <td><%= image_tag profile.profile_pic.url(:thumb).to_s, class: "img-rounded" %></td>
        <td><%= profile.user_id %></td>
        <td><%= link_to 'Show', profile, class: "btn btn-warning" %></td>
        <% if current_user.profile.id == profile.id %>
        <td><%= link_to 'Edit', edit_profile_path(profile), class: "btn btn-info" %></td>
        <td><%= link_to 'Delete', profile, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger" %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<!-- <%= link_to 'New Profile', new_profile_path, class: "btn btn-warning" %> -->

app/views/profiles/new.html.erb
<div class="container">
<div class="jumbotron">
<h1>Create Your Profile</h1>

<%= render 'form' %>
<div class="pull-right" style="margin-right: 0%">
<%= link_to 'Back', profiles_path, class: "btn btn-primary" %>
</div>
</div>
</div>

app/views/profiles/show.html.erb
<div class="container">
<div class="jumbotron">
<p id="notice"><%= notice %></p>


<p>
  <%= image_tag @profile.profile_pic_url(:big).to_s, class: "img-rounded img-responsive" %><br>
</p>

<p>
  <strong>Name:</strong>
  <%= @profile.name %>
</p>

<p>
  <strong>Location:</strong>
  <%= @profile.location %>
</p>


<p>
  <strong>Email:</strong>
  <%= @profile.user.email %>
</p>

<% if current_user.profile.id == @profile.id %>
<%= link_to 'Edit', edit_profile_path(@profile), class: "btn btn-warning" %> |
<% end %>
<%= link_to 'Back', profiles_path, class: "btn btn-primary" %> |
<%= link_to 'Create New Listing', new_listing_path, class:"btn btn-success" %> |
<%= link_to "Explore Listings", listings_index_path, method: :get, class:"btn btn-info" %>

<br>
<br>
</div>
</div>