config/routes.rb
Rails.application.routes.draw do
  resources :reservations
  resources :profiles
  get 'listings/create'

  get 'listings/new'

  get 'listings/show'

  get 'listings/index'

  get 'listings/update'

  get 'listings/edit'

  get 'listings/destroy'

  get 'search', to: 'search#search'

  resources :passwords, controller: "clearance/passwords", only: [:create, :new]
  resource :session, controller: "clearance/sessions", only: [:create]

  resources :users, controller: "clearance/users", only: [:create] do
    resource :password,
      controller: "clearance/passwords",
      only: [:create, :edit, :update]
  end

  resources :users, only: [:show, :edit, :update, :destroy] 

  resources :listings 

  resources :transactions, only: [:new, :create]

  resources :users, only:[:create, :new, :show, :edit, :update, :destroy, :index] do
    resources :listings
  end

  resources :users, only:[:create, :new, :show, :edit, :update, :destroy, :index] do
    resources :reservations
  end

   resources :users, only:[:create, :new, :show, :edit, :update, :destroy] do
    resources :profile, except:[:index]
  end

  get "/sign_in" => "clearance/sessions#new", as: "sign_in"
  delete "/sign_out" => "clearance/sessions#destroy", as: "sign_out"
  get "/sign_up" => "clearance/users#new", as: "sign_up"
  get "/auth/:provider/callback" => "sessions#create_from_omniauth"

  root 'users#index'

end

app/models/listing.rb
class Listing < ActiveRecord::Base
	belongs_to :user
	has_many :reservations, :dependent => :destroy
	validates_presence_of :price_per_night, :home_type, :room_type, :accommodates, :address, :city, :name, :listingpics
	mount_uploaders :listingpics, ListingpicUploader
	searchkick
end

app/controllers/listings_controller.rb
class ListingsController < ApplicationController
before_action :set_listing, only: [:show, :edit, :update, :destroy]
before_action :require_login, only: [:edit, :update, :destroy, :create, :new]

  def create
    @user = current_user
    @listing = @user.listings.new(listing_params)

    # @listing = Listing.new(listing_params)

    respond_to do |format|
      if @listing.save
        format.html { redirect_to @listing, notice: 'Listing was successfully created.' }
        format.json { render :show, status: :created, location: @listing }
      else
        format.html { render :new }
        format.json { render json: @listing.errors, status: :unprocessable_entity }
      end
    end
  end

  def new
    @listing = Listing.new
  end

  def show
    @listing_reservations = []
    
    @listing.reservations.each do |booking|
    @listing_reservations << booking
    end

  end

  def index
    return @listings = Listing.paginate(:page => params[:page], per_page: 1).where(user_id: params[:user_id]) if params[:user_id]
    @listings = Listing.paginate(:page => params[:page], per_page: 5).order(created_at: :desc)
  end

  def update
    # @user = current_user
    # byebug
    # Don't need user_id in params by doing @user.listing.update because you don't want to change the user_id
        respond_to do |format|
      if @listing.update(listing_params)
        format.html { redirect_to @listing, notice: 'Listing was successfully updated.' }
        format.json { render :show, status: :ok, location: @listing }
      else
        format.html { render :edit }
        format.json { render json: @listing.errors, status: :unprocessable_entity }
      end
    end
  end

  def edit
  end

  def destroy
        @listing.destroy
    respond_to do |format|
      format.html { redirect_to listings_url, notice: 'Listing was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_listing
      @listing = Listing.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def listing_params
      # params[:listing][:user_id] = current_user.id
      params.require(:listing).permit(:name, :home_type, :room_type, :accommodates, :address, :city, :user_id, :price_per_night, { :listingpics => [] })
    end
end

app/helpers/listings_helper.rb
module ListingsHelper
end

app/views/listings/_form.html.erb
<%= form_for(@listing) do |f| %>
<% if @listing.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@listing.errors.count, "error") %> prohibited this listing from being saved:</h2>

      <ul>
      <% @listing.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name, class: "form-control" %>
  </div>
  <div class="field">
    <%= f.label :home_type %><br>
    <%= f.text_field :home_type, class: "form-control" %>
  </div>
  <div class="field">
    <%= f.label :room_type %><br>
    <%= f.text_field :room_type, class: "form-control" %>
  </div>
  <div class="field">
    <%= f.label :accommodates %><br>
    <%= f.number_field :accommodates, class: "form-control" %>
  </div>
  <div class="field">
    <%= f.label :address %><br>
    <%= f.text_area :address, class: "form-control" %>
  </div>
  <div class="field">
    <%= f.label :city %><br>
    <%= f.text_field :city, class: "form-control" %>
  </div>
    <div class="field">
    <%= f.label :price_per_night_in_USD %><br>
    <%= f.number_field :price_per_night, class: "form-control" %>
  </div>
     <div class="field">
    <%= f.label :listingpics %><br>
    <%= f.file_field :listingpics, multiple: true %>
  </div>
  <br>
  <div class="actions">
    <%= f.submit "Confirm Listing Details", class: "btn btn-success" %>
  </div>
  <%end%>

app/views/listings/create.html.erb
<h1>Create A New Listing</h1>

app/views/listings/destroy.html.erb
<h1>Delete Your Listing</h1>

app/views/listings/edit.html.erb
<div class="container">
<div class="jumbotron">

<h1>Edit Listing</h1>

<%= render 'form' %>
<div class="pull-right" style="margin-right: 2%">
<%= link_to 'Show', @listing, class: "btn btn-warning" %> |
<%= link_to 'Back', listings_path, class: "btn btn-primary" %>
</div>
<br>
<br>
<br>

</div>
</div>

app/views/listings/index.html.erb
    <div id="myCarousel" class="carousel slide" data-ride="carousel" style="margin-top: -100px;">
      <!-- Indicators -->
      <ol class="carousel-indicators">
        <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
        <li data-target="#myCarousel" data-slide-to="1"></li>
        <li data-target="#myCarousel" data-slide-to="2"></li>
      </ol>
      <div class="carousel-inner" role="listbox">
        <div class="item active">
        <div class="videoWrapper">
          <iframe width="1280" height="720" src="https://www.youtube.com/embed/Ba5fqHENsoo?rel=0&autoplay=1&controls=0&loop=1&playlist=Ba5fqHENsoo&showinfo=0" frameborder="0" allowfullscreen="" ></iframe>
          </div>

              <!--  <video autoplay loop width="100%">
                 <source src="http://clips.vorwaerts-gmbh.de/big_buck_bunny.mp4" width="1024" height="552" type="video/mp4">
                 Your browser does not support the video tag.
              </video> -->
          <div class="container">
            <div class="carousel-caption">
              <h1 id="cap-text">Find Your Next Adventure Today!</h1>
              <form class="form-wrapper cf" action="/search/?q=" method="get">
              <input id="johnson-input" type="text" placeholder="Where's your next adventure gonna be?" name="q">
              <button id="johnson-btn" type="submit">Search</button>
              </form>
              <!-- <p>Note: If you're viewing this page via a <code>file://</code> URL, the "next" and "previous" Glyphicon buttons on the left and right might not load/display properly due to web browser security rules.</p>
              <p><a class="btn btn-lg btn-primary" href="#" role="button"><span class="glyphicon glyphicon-star" aria-hidden="true"></span> Date Them Now!</a></p> -->
            </div>
          </div>
        </div>
        <div class="item">
        <div class="videoWrapper">
          <iframe width="1280" height="720" src="https://www.youtube.com/embed/QALNwcA3EQQ?rel=0&autoplay=1&controls=0&loop=1&playlist=QALNwcA3EQQ&showinfo=0" frameborder="0" allowfullscreen="" ></iframe>
          </div>
              <!--  <video autoplay loop width="100%">
                 <source src="http://clips.vorwaerts-gmbh.de/big_buck_bunny.mp4" width="1024" height="552" type="video/mp4">
                 Your browser does not support the video tag.
              </video> -->
          <div class="container">
            <div class="carousel-caption">
              <h1 id="cap-text">Travel The World In Style! </h1>
              <form class="form-wrapper cf" action="/search/?q=" method="get">
              <input id="johnson-input" type="text" placeholder="Where's your next adventure gonna be?" name="q">
              <button id="johnson-btn" type="submit">Search</button>
              </form>
 

              <!-- <p>Cras justo odio, dapibus ac facilisis in, egestas eget quam. Donec id elit non mi porta gravida at eget metus. Nullam id dolor id nibh ultricies vehicula ut id elit.</p>
              <p><a class="btn btn-lg btn-primary" href="#" role="button">Try Raz's Cooking Today!</a></p> -->
            </div>
          </div>
        </div>
        <div class="item">
        <div class="videoWrapper">
          <iframe width="1280" height="720" src="https://www.youtube.com/embed/49z9b2lgB6k?rel=0&autoplay=1&controls=0&loop=1&playlist=49z9b2lgB6k&showinfo=0" frameborder="0" allowfullscreen="" ></iframe>
          </div>
              <!--  <video autoplay loop width="100%">
                 <source src="http://clips.vorwaerts-gmbh.de/big_buck_bunny.mp4" width="1024" height="552" type="video/mp4">
                 Your browser does not support the video tag.
              </video> -->
          <div class="container">
            <div class="carousel-caption">
              <h1 id="cap-text">Raz & Kevin Will Rock You!</h1>
              <div>
              <form class="form-wrapper cf" action="/search/?q=" method="get">
              <input id="johnson-input" type="text" placeholder="Where's your next adventure gonna be?" name="q">
              <button id="johnson-btn" type="submit">Search</button>
              </form>
              </div>
             <!--  <p>Cras justo odio, dapibus ac facilisis in, egestas eget quam. Donec id elit non mi porta gravida at eget metus. Nullam id dolor id nibh ultricies vehicula ut id elit.</p>
              <p><a class="btn btn-lg btn-primary" href="#" role="button">Sign Up Now!</a></p> -->
            </div>
          </div>
        </div>
      </div>
      <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
        <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
      </a>
      <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
        <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
      </a>
    </div><!-- /.carousel -->


<!-- ========================================================================= -->
<!-- 
<form id="searchForm" action="/search/?q=" method="get"><input class="nice_search" type="text" name="q" placeholder="Search...">
 <input class="nice_submit" type="submit" value="SEARCH"></form>

<script type="text/javascript">
 $('#searchForm').submit(function(e){
   e.preventDefault();
   var search = $('.nice_search').val();
   var url = $(this).attr('action');
   //alert('search='+search+ ' url='+url);
   window.location.href = url+search;
});

</script>

<br> -->


<p id="notice"><%= notice %></p>

<!-- <h1>Listing Listings</h1>

<%= will_paginate @listings %> <br>
<table width=100%>
  <thead>
    <tr>
      <th>Name</th>
      <th>Pictures</th>
      <th>Price/Night</th>
      <th>Home type</th>
      <th>Room type</th>
      <th>Accommodates</th>
      <th>Address</th>
      <th>City</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @listings.each do |listing| %>
      <tr>
        <td><%= listing.name %></td>
        <% if listing.listingpics.blank? == true %>
        <td>No Pics Available</td>
        <% else %>
        <td><% listing.listingpics.each do |listingpic| %>
        <%= image_tag listingpic.url(:thumb).to_s, class: "img-rounded" %><b>
        <% end %>
        </td>
        <% end %>
        <td><%= listing.price_per_night %></td>
        <td><%= listing.home_type %></td>
        <td><%= listing.room_type %></td>
        <td><%= listing.accommodates %></td>
        <td><%= listing.address %></td>
        <td><%= listing.city %></td>
        <% if listing.user.profile != nil %>
        <td><%= image_tag listing.user.profile.profile_pic_url(:thumb).to_s, class: "img-circle" %><%= link_to "#{listing.user.profile.name}", profile_path(listing.user.profile.id) %></td>
        <% else %>
        <td><%= listing.user.email %></td>
        <% end %>
        <td><%= link_to 'Show', listing %></td>
         <% if listing.user == current_user %>
        <td><%= link_to 'Edit', edit_listing_path(listing) %></td>
        <td><%= link_to 'Destroy', listing, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>
<br>
<%= will_paginate @listings %> <br>

<br>

<%= link_to 'New Listing', new_listing_path %> -->

<div class="jumbotron" style="margin-top: -20px;">
  <h1>Listings</h1>
</form>
</div>

<div class="container">
<h3 style="text-align: right"><%= link_to 'Create New Listing', new_listing_path, class:"btn btn-info pull-left" %><%= will_paginate @listings %></h3>
</div>
<div class="container-fluid"><br><br></div>
<div class="container">

 <% @listings.each do |listing| %>
   <div class="row"><!-- Full Row -->      
     <div class="col-lg-5"><!-- Picture Box-->
     <% if listing.listingpics.blank? == true %>
     <p>No Pics Available</p>
     <% else %>
       <%= image_tag listing.listingpics.first.url(:mid).to_s, class: 'img-responsive' %>
     <% end %>
     </div><!-- End Picture Box -->
     <div class="col-lg-5"><!-- Info Box -->
       <h3><%= link_to "#{listing.name}", listing %></h3>
       <p><strong>Home type:</strong> <%= listing.home_type %></p>
       <p><strong>Room type:</strong> <%= listing.room_type %></p>
       <p><strong>Accomodates:</strong> <%= listing.accommodates %></p>
       <p><strong>Address:</strong> <%= listing.address %></p>
       <p><strong>City:</strong> <%= listing.city %></p>
     </div><!-- End Info Box -->
     <div class="col-lg-2"><!-- User Box -->
       <p>Posted by:</p>
       <p><%= image_tag listing.user.profile.profile_pic_url(:thumb).to_s, class:"img-circle" %> <%= link_to "#{listing.user.profile.name}", profile_path(listing.user.profile) %></p>
       <% if listing.user == current_user %>
         <p>
           <%= link_to 'Edit', edit_listing_path(listing), class:"btn btn-warning" %>
           <%= link_to 'Delete', listing, method: :delete, data: { confirm: 'Are you sure?' }, class:"btn btn-danger" %>
         </p>
       <% end %>   
       <p class="lead"><strong>Price/Night:</strong><br><span class="label label-success"><%= listing.price_per_night %> USD </span></p>      
     </div><!-- End User Box -->
     <hr>
   </div><!-- End Full Row -->
   <hr>
 <% end %>
<h3 style="text-align: right"><%= link_to 'Create New Listing', new_listing_path, class:"btn btn-info pull-left" %><%= will_paginate @listings %></h3> <br>
</div>
<div class="container-fluid"><br><br></div>

app/views/listings/new.html.erb
<div class="container">
<div class="jumbotron">

<h1>List Your Amazing Place Now!</h1>

<%= render 'form' %>

<div class="pull-right" style="margin-right: 0%">
<%= link_to 'Back', listings_path, class: "btn btn-primary" %>
</div>
<br>


</div>
</div>

app/views/listings/show.html.erb
<% unless notice.blank? %>
<div class="alert alert-success" role="alert">
<p id="notice"><%= notice %></p>
</div>
<%end%>

<% if @listing.listingpics.blank? == true %>
 <h2>No Pictures Available</h2>
 <% else %>

<div class="carousel slide" id="screenshot-carousel" data-rise="carousel" style="margin-top: -100px;"><!-- Variable Carousel -->
       <ol class="carousel-indicators">
         <% @listing.listingpics.each_with_index do |listingpic, index| %>
           <% if index == 0 %>
             <li data-target="screenshot-carousel" data-slide-to="#{index}" class="active"></li>            
           <% else %>
             <li data-target="screenshot-carousel" data-slide-to="#{index}"></li>
           <% end %>
         <% end %>
       </ol>
       <div class="carousel-inner">
         <% @listing.listingpics.each_with_index do |listingpic, index| %>
           <% if index == 0 %>
             <div class="item active">
            
               <%= image_tag listingpic.url(:full).to_s, class: "picpic" %>
            
             </div>
           <% else %>
             <div class="item">
             
               <%= image_tag listingpic.url(:full).to_s, class: "picpic" %>
            
             </div>
           <% end %>            
         <% end %>
       </div>
       <a href="#screenshot-carousel" class="left carousel-control" data-slide="prev">
         <span class="glyphicon glyphicon-chevron-left"></span>
       </a>
       <a href="#screenshot-carousel" class="right carousel-control" data-slide="next">
         <span class="glyphicon glyphicon-chevron-right"></span>
       </a>
     </div><!-- End Variable Carousel -->


<% end %>

<div style="background: black">
 <div class="container-fluid" style="">
   <div class="row">
  <% @listing.listingpics.each do |listingpic| %>
  <div class="col-md-4" style="padding: 0px;">
  <%= image_tag listingpic.url(:mid).to_s, class: "img-rounded img-responsive", style: "width: 100%;height: auto;"%>
  </div>
  <% end %>
</div>
</div>
</div>

<!-- 

 <% if @listing.listingpics.blank? == true %>
 <h2>No Pictures Available</h2>
 <% else %>
 <div id="myCarousel" class="carousel slide" data-ride="carousel"> -->
      <!-- Indicators -->
    <!--   <ol class="carousel-indicators">
        <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
        <li data-target="#myCarousel" data-slide-to="1"></li>
        <li data-target="#myCarousel" data-slide-to="2"></li>
      </ol>
      <div class="carousel-inner" role="listbox">
      <div class="item active">
          <%= image_tag @listing.listingpics[0].url(:full).to_s, class: "img-rounded" %>
      </div>


       <% @listing.listingpics.each do |listingpic| %>
        <div class="item">
          <%= image_tag listingpic.url(:full).to_s, class: "img-rounded" %>
        </div>
        <%end%>
       
      </div>
      <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
        <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
      </a>
      <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
        <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
      </a>
    </div> -->
    <!-- /.carousel -->

<!-- <%end%> -->

<div class="container">
<div class="jumbotron">
 
<h1><%= @listing.name %></h1> 
<br>

<p class="lead">
  <strong>Home Type:</strong>
  <%= @listing.home_type %>
</p>

<p class="lead">
  <strong>Room Type:</strong>
  <%= @listing.room_type %>
</p>

<p class="lead">
  <strong>Accommodates:</strong>
  <%= @listing.accommodates %>
</p>

<p class="lead">
  <strong>Address:</strong>
  <%= @listing.address %>
</p>

<p class="lead">
  <strong>City:</strong>
  <%= @listing.city %>
</p>

<p class="lead">
  <strong>Listing Owner:</strong>
  <% if @listing.user.profile.blank? %>
  <%= @listing.user.email %>
  <% else %>
  <%= @listing.user.profile.name %>
  <% end %>
</p>
<div class="row">
<p class="lead">
  <strong>Price Per Night:</strong>
  <span class="label label-pill label-danger"><%= @listing.price_per_night %> USD </span>
</p>
</div>

<br>

<% if @listing.user == current_user %>
<%= link_to 'Edit', edit_listing_path(@listing), class: "btn btn-warning" %> |
<% end %>
<%= link_to 'Back', listings_path, class: "btn btn-primary" %>
<div class="pull-right">
<%= link_to 'Make A Reservation', new_reservation_path(:listing_id => @listing.id), class: "btn btn-success" %>
</div>
</div>
</div>


<div class="container">
<div class="table-responsive">
<table width="100%" class="table table-striped">
  <thead>
    <tr>
      <th>ID </th>
      <th>Reservations</th>
      <th>Duration</th>
      <th style="text-align: right">Check In Date</th>
      <th style="text-align: right">Check Out Date</th>
    </tr>
  </thead>

  <tbody>
    <% if @listing_reservations.empty? %>
    <tr>
    <td colspan="5" style="text-align: center"><h2><span class="label label-danger"> No reservations yet</span></h2></td>
    </tr>
    <tr>
    <td colspan="5" style="text-align: center">
    <%= link_to 'Be The First To Book This Awesome Place!', new_reservation_path(:listing_id => @listing.id), class: "btn btn-lg btn-success" %>
    </td>
    </tr>
    <% else %>

    <% @listing_reservations.each.with_index do |booking, index| %>
      <tr>
        <td><%= index + 1 %></td>
        <% if booking.user.profile.blank? %>
        <td><%= booking.user.email %></td>
        <% else %>
        <td><%= image_tag booking.user.profile.profile_pic.url(:thumb).to_s, class: "img-rounded" %> <%= booking.user.profile.name %></td>
        <%end%>
        <td><h4><span class="label label-danger"><%= (booking.checkout - booking.checkin).to_i.to_s + " Day (s) " %></span></h4></td>
        <td style="text-align: right"><h4><span class="label label-success"><%= booking.checkin %></span></h4></td>
        <td style="text-align: right"><h4><span class="label label-warning"><%=  booking.checkout %></span></h4></td>
      </tr>
    <% end %>
    <% end %>
  </tbody>
</table>
</div>

<!-- 
<br>
<p>
  <strong> Reservations:</strong>
  <% @listing.reservations.each.with_index do |booking, index| %>
  <p><%= index + 1 %>  From:  <%= booking.checkin %>   To:  <%=  booking.checkout %>   -- Booked By: <%= booking.user.profile.name %>  

  <% if current_user == booking.user %>
  <%= link_to 'Destroy', reservation_path(:id => booking.id), method: :delete, data: { confirm: 'Are you sure?' } %>
  <%end%>
  </p>
  <% end %>
</p> -->
</div>

<br>
<br>
<br>


<!-- 

<p>
  <strong>Name:</strong>
  <%= @listing.name %>
</p>

<p>
  <strong>Home type:</strong>
  <%= @listing.home_type %>
</p>

<p>
  <strong>Room type:</strong>
  <%= @listing.room_type %>
</p>

<p>
  <strong>Accommodates:</strong>
  <%= @listing.accommodates %>
</p>

<p>
  <strong>Address:</strong>
  <%= @listing.address %>
</p>

<p>
  <strong>City:</strong>
  <%= @listing.city %>
</p>

<p>
  <strong>User:</strong>
  <%= @listing.user.email %>
</p>

<p>
  <strong>Price Per Night:</strong>
  <%= @listing.price_per_night %>
</p> -->
<!-- 
 <% if @listing.listingpics.blank? == true %>
 <h2>No Pictures Available</h2>
 <% else %>

<div class="carousel slide" id="screenshot-carousel" data-rise="carousel"> -->

<!-- Variable Carousel -->
     <!--   <ol class="carousel-indicators">
         <% @listing.listingpics.each_with_index do |listingpic, index| %>
           <% if index == 0 %>
             <li data-target="screenshot-carousel" data-slide-to="#{index}" class="active"></li>            
           <% else %>
             <li data-target="screenshot-carousel" data-slide-to="#{index}"></li>
           <% end %>
         <% end %>
       </ol>
       <div class="carousel-inner">
         <% @listing.listingpics.each_with_index do |listingpic, index| %>
           <% if index == 0 %>
             <div class="item active">
               <%= image_tag listingpic.url(:full).to_s %>
             </div>
           <% else %>
             <div class="item">
               <%= image_tag listingpic.url(:full).to_s %>
             </div>
           <% end %>            
         <% end %>
       </div>
       <a href="#screenshot-carousel" class="left carousel-control" data-slide="prev">
         <span class="glyphicon glyphicon-chevron-left"></span>
       </a>
       <a href="#screenshot-carousel" class="right carousel-control" data-slide="next">
         <span class="glyphicon glyphicon-chevron-right"></span>
       </a>
     </div> -->
     <!-- End Variable Carousel -->

<!-- <% end %> -->

<!-- <p>
  <strong> Reservations:</strong>
  <% @listing.reservations.each.with_index do |booking, index| %>
  <p><%= index + 1 %>  From:  <%= booking.checkin %>   To:  <%=  booking.checkout %>   -- Booked By: <%= booking.user.profile.name %>  

  <% if current_user == booking.user %>
  <%= link_to 'Destroy', reservation_path(:id => booking.id), method: :delete, data: { confirm: 'Are you sure?' } %>
  <%end%>
  </p>
  <% end %>
</p> -->

<!--  <% if @listing.user == current_user %>
<%= link_to 'Edit', edit_listing_path(@listing) %> |
<% end %>
<%= link_to 'Back', listings_path %>
<br>
<%= link_to 'Make A Reservation', new_reservation_path(:listing_id => @listing.id) %> -->

app/views/listings/update.html.erb
<h1>Listings#update</h1>
<p>Find me in app/views/listings/update.html.erb</p>