config/routes.rb
Rails.application.routes.draw do
  resources :reservations
  resources :profiles
  get 'listings/create'

  get 'listings/new'

  get 'listings/show'

  get 'listings/index'

  get 'listings/update'

  get 'listings/edit'

  get 'listings/destroy'

  get 'search', to: 'search#search'

  resources :passwords, controller: "clearance/passwords", only: [:create, :new]
  resource :session, controller: "clearance/sessions", only: [:create]

  resources :users, controller: "clearance/users", only: [:create] do
    resource :password,
      controller: "clearance/passwords",
      only: [:create, :edit, :update]
  end

  resources :users, only: [:show, :edit, :update, :destroy] 

  resources :listings 

  resources :transactions, only: [:new, :create]

  resources :users, only:[:create, :new, :show, :edit, :update, :destroy, :index] do
    resources :listings
  end

  resources :users, only:[:create, :new, :show, :edit, :update, :destroy, :index] do
    resources :reservations
  end

   resources :users, only:[:create, :new, :show, :edit, :update, :destroy] do
    resources :profile, except:[:index]
  end

  get "/sign_in" => "clearance/sessions#new", as: "sign_in"
  delete "/sign_out" => "clearance/sessions#destroy", as: "sign_out"
  get "/sign_up" => "clearance/users#new", as: "sign_up"
  get "/auth/:provider/callback" => "sessions#create_from_omniauth"

  root 'users#index'

end

app/models/reservation.rb
class Reservation < ActiveRecord::Base
	belongs_to :user
	belongs_to :listing
	has_many :transactions, :dependent => :destroy
	validates_presence_of :checkin, :checkout

	def total_price
		total_price = 0
		days = (self.checkout - self.checkin).to_i 
		total_price = days*(self.listing.price_per_night)
		return total_price
	end
end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController
  before_action :set_reservation, only: [:show, :edit, :update, :destroy]
  before_action :require_login

  # GET /reservations
  # GET /reservations.json
  def index
    return @reservations = Reservation.where(user_id: params[:user_id]) if params[:user_id]
    @reservations = Reservation.all
  end

  # GET /reservations/1
  # GET /reservations/1.json
  def show
  end

  # GET /reservations/new
  def new
    @listing_id = params[:listing_id]
    # byebug
    @reservation = Reservation.new
  end

  # GET /reservations/1/edit
  def edit
  end

  # POST /reservations
  # POST /reservations.json
  def create
    @reservation = Reservation.new(reservation_params)

    # byebug

    respond_to do |format|
      if @reservation.save

        # byebug


        @listing = Listing.find(params[:reservation][:listing_id])

        @user = @listing.user

        @reserver = User.find(params[:reservation][:user_id])

        # byebug

        ReservationMailer.delay.reservation_email(@user, @listing, @reserver)
        ReservationMailer.delay.confirmation_email(@user, @listing, @reserver)

        ReservationMailer.reservation_email(@user, @listing, @reserver).deliver
        ReservationMailer.confirmation_email(@user, @listing, @reserver).deliver

        # byebug


        format.html { redirect_to @reservation, notice: 'Reservation was successfully created.' }
        format.json { render :show, status: :created, location: @reservation }
      else
        format.html { render :new }
        format.json { render json: @reservation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /reservations/1
  # PATCH/PUT /reservations/1.json
  def update
    respond_to do |format|
      if @reservation.update(reservation_params)
        format.html { redirect_to @reservation, notice: 'Reservation was successfully updated.' }
        format.json { render :show, status: :ok, location: @reservation }
      else
        format.html { render :edit }
        format.json { render json: @reservation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reservations/1
  # DELETE /reservations/1.json
  def destroy
    @reservation.destroy
    respond_to do |format|
      format.html { redirect_to reservations_url, notice: 'Reservation was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_reservation
      @reservation = Reservation.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def reservation_params
      params.require(:reservation).permit(:checkin, :checkout, :specialrequests, :user_id, :listing_id)
    end
end

app/helpers/reservations_helper.rb
module ReservationsHelper
end

app/views/reservations/_form.html.erb
<%= form_for(@reservation) do |f| %>
  <% if @reservation.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@reservation.errors.count, "error") %> prohibited this reservation from being saved:</h2>

      <ul>
      <% @reservation.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

    <div>
    <%= image_tag Listing.find(@listing_id).listingpics.first.url(:mid).to_s, class: "img-rounded img-responsive" %>
  </div>
    <div>
    <h2><%= Listing.find(@listing_id).name %></h2>
  </div>

  <div class="field">
    <%= f.label :checkin %><br>
    <%= f.date_field :checkin, class: "form-control" %>
  </div>
  <div class="field">
    <%= f.label :checkout %><br>
    <%= f.date_field :checkout, class: "form-control" %>
  </div>
  <div class="field">
    <%= f.label :specialrequests %><br>
    <%= f.text_area :specialrequests, class: "form-control" %>
  </div>
  <div class="field">
    <%= f.hidden_field :user_id, value: current_user.id %>
  </div>
  <div class="field">
    <%= f.hidden_field :listing_id, value: @listing_id %>
  </div>
  <br>
  <div class="actions">
    <%= f.submit "Confirm Reservation", class: "btn btn-success" %>
  </div>
  <div class="pull-right" style="margin-right: 0%">
  <%= link_to 'Back To All Listings' , listings_index_path, class: "btn btn-warning" %>
  </div>
<% end %>

app/views/reservations/edit.html.erb
<h1>Editing Reservation</h1>

<%= render 'form' %>

<%= link_to 'Show', @reservation, class: "btn btn-warning" %> |
<%= link_to 'Back', reservations_path, class: "btn btn-primary" %>

app/views/reservations/index.html.erb
<div class="jumbotron">
<p id="notice"><%= notice %></p>

<h1>All Reservations</h1>

<div class="table-responsive">
<table width="100%" class="table table-condensed table-striped">
  <thead>
    <tr>
      <th>Checkin</th>
      <th>Checkout</th>
      <th>Special Requests</th>
      <th>Listing Owner</th>
      <th>Reserved By</th>
      <th>Listing</th>
      <th>Duration</th>
      <th>Total Cost</th>
      <th>Payment Status</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @reservations.each do |reservation| %>
      <tr>
        <td><%= reservation.checkin %></td>
        <td><%= reservation.checkout %></td>
        <td><%= reservation.specialrequests %></td>
        <td><%= image_tag reservation.listing.user.profile.profile_pic.url(:thumb).to_s, class: "img-rounded" %> <%= reservation.listing.user.profile.name %></td>
        <td><%= image_tag reservation.user.profile.profile_pic.url(:thumb).to_s, class: "img-rounded" %> <%= reservation.user.profile.name %></td>
        <td><%= image_tag reservation.listing.listingpics.first.url(:thumb).to_s, class: "img-rounded" %> <%= link_to "#{reservation.listing.name}", listing_path(reservation.listing.id) %></td>
        <td class="lead" style="text-align: center"><span class="label label-success"><%= (reservation.checkout - reservation.checkin).to_i %> Day (s)</span></td>
        <td class="lead" style="text-align: center"><span class="label label-primary">$<%= reservation.total_price %> USD</span> </td>
        <% if reservation.transactions.where(status: :authorized).blank? %>
        <td style="text-align: center"><%= link_to '<button class="btn btn-danger" type="button">Pay Now</button>'.html_safe , new_transaction_path + "?id=" + reservation.id.to_s %> </td>
        <% else %>
        <td class="lead" style="text-align: center"><span class="label label-success"> PAID </span></td>
        <% end %>
        <td><%= link_to 'Show', reservation, class: "btn btn-info" %></td>
        <td><%= link_to 'Delete', reservation, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-warning" %></td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>

<br>
<div class="pull-right" style="margin-right: 1%">
<%= link_to 'All Listings' , listings_index_path, class: "btn btn-danger" %>
<br>
</div>

</div>

app/views/reservations/new.html.erb
<div class="container">
<div class="jumbotron">
<h1>New Reservation</h1>

<%= render 'form' %>

<br>
</div>
</div>

app/views/reservations/show.html.erb
<div class="container">
<div class="jumbotron">
<p id="notice"><%= notice %></p>

<p class="lead">
  <%= image_tag @reservation.listing.listingpics.first.url(:mid).to_s, class: "img-rounded img-responsive" %>
</p>

<h2>
  <%= @reservation.listing.name %>
</h2>

<h3><span class="label label-primary"> Booked </span></h3>
<br>

<p class="lead">
  <strong>Checkin:</strong>
  <%= @reservation.checkin %>
</p>

<p class="lead">
  <strong>Checkout:</strong>
  <%= @reservation.checkout %>
</p>

<p class="lead">
  <strong>Special Requests:</strong>
  <%= @reservation.specialrequests %>
</p>

<p class="lead">
  <strong>Reserved By:</strong>
  <%= @reservation.user.profile.name %>
</p>

<p class="lead">
  <strong>Total Amount Due:</strong>
  <span class="label label-danger"><%= @reservation.total_price %> USD</span>
</p>

<p class="lead">
  <strong>Payment Status:</strong>
<% if @reservation.transactions.where(status: :authorized).blank? %>
<span class="label label-warning"> NOT PAID </span> || <%= link_to 'Pay Now' , new_transaction_path + "?id=" + @reservation.id.to_s, class: "btn btn-success"  %>
<% else %>
<span class="label label-success">PAID</span>
<% end %>
</p>

<div class="pull-right" style="margin-right: 0%">
<%= link_to 'Back To All Listings' , listings_index_path, class: "btn btn-info" %>
</div>





<!-- 
<%= link_to 'All Listings' , listings_index_path %>

<br>

<% if @reservation.transactions.where(status: :authorized).blank? %>
<h2>Payment Status: NOT PAID</h2>

<%= link_to 'Pay Now' , new_transaction_path + "?id=" + @reservation.id.to_s  %>
<% else %>
<h2>Payment Status: PAID</h2><br>

<% end %> -->

<br>
<br>

</div>
</div>