config/routes.rb
Rails.application.routes.draw do
  resources :reservations
  resources :profiles
  get 'listings/create'

  get 'listings/new'

  get 'listings/show'

  get 'listings/index'

  get 'listings/update'

  get 'listings/edit'

  get 'listings/destroy'

  get 'search', to: 'search#search'

  resources :passwords, controller: "clearance/passwords", only: [:create, :new]
  resource :session, controller: "clearance/sessions", only: [:create]

  resources :users, controller: "clearance/users", only: [:create] do
    resource :password,
      controller: "clearance/passwords",
      only: [:create, :edit, :update]
  end

  resources :users, only: [:show, :edit, :update, :destroy] 

  resources :listings 

  resources :transactions, only: [:new, :create]

  resources :users, only:[:create, :new, :show, :edit, :update, :destroy, :index] do
    resources :listings
  end

  resources :users, only:[:create, :new, :show, :edit, :update, :destroy, :index] do
    resources :reservations
  end

   resources :users, only:[:create, :new, :show, :edit, :update, :destroy] do
    resources :profile, except:[:index]
  end

  get "/sign_in" => "clearance/sessions#new", as: "sign_in"
  delete "/sign_out" => "clearance/sessions#destroy", as: "sign_out"
  get "/sign_up" => "clearance/users#new", as: "sign_up"
  get "/auth/:provider/callback" => "sessions#create_from_omniauth"

  root 'users#index'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
<meta property="og:url" content="https://johnsonbbnb.herokuapp.com/" />
<meta property="og:url" content="http://johnsonbbnb.herokuapp.com/" />
<meta property="og:type" content="article" />
<meta property="og:title" content="Johnson BBnB" />
<meta property="og:description" content="A basic rails based AirBnB clone I built during my 8-week programming bootcamp at NEXT Academy" />
<meta property="og:image" content="http://wowwwz.com/wp-content/uploads/2016/04/bbnbhomepic44.jpg" />


<link href="//netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css" rel="stylesheet">
<!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">

<!-- Optional theme -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap-theme.min.css" integrity="sha384-fLW2N01lMqjakBkx3l/M9EahuwpSfeNvV63J5ezn3uZzapT0u7EYsXMjQV+0En5r" crossorigin="anonymous">

<meta name="viewport" content="width=device-width, initial-scale=1.0">
<%= javascript_include_tag 'application'%>
<%= stylesheet_link_tag 'application'%>
  <%= csrf_meta_tag %>
</head>
<body>
<!-- <div class="navbar-wrapper">
      <div class="container"> -->

        <nav class="navbar navbar-inverse navbar-static-top">
          <div class="container">
            <div class="navbar-header">
              <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
              </button>
              <a class="navbar-brand" href="#"> Johnson BBnB </a>
            </div>
            <div id="navbar" class="navbar-collapse collapse">
              <ul class="nav navbar-nav">
                <li><a href="/">Home</a></li>
                <li><%= link_to "All Listings", listings_index_path, method: :get %></li>
                <% if signed_in? %>
                <li class="dropdown">
                  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Your Account <span class="caret"></span></a>
                  <ul class="dropdown-menu">
                    <% if current_user.profile == nil %>
                    <li><%= link_to 'Create Your Profile', new_profile_path %></li>
                    <% else %>
                    <li><%= link_to 'Your Profile', profile_path(current_user.profile.id) %></li>
                    <% end %>
                    <li><%= link_to "Your Listings", user_listings_path(current_user.id) %></li>
                    <li><%= link_to "Your Reservations", user_reservations_path(current_user.id) %></li>
                    <li role="separator" class="divider"></li>
                    <li class="dropdown-header">Unpaid Reservations</li>
                    <% @reservations = current_user.reservations %>
                    <% @unpaid_reservations = [] %>
                    <% @reservations.each do |reservation| %>
                    <% if reservation.transactions.where(status: :authorized).blank? %>
                    <% @unpaid_reservations << reservation %>
                    <% end %>
                    <% end %>
                    <% if @unpaid_reservations.empty? %>
                    <li style="text-align: center"> None </li>
                    <% else %>
                    <% @unpaid_reservations.each_with_index do |reservation, index| %> 
                    <li><%= link_to "#{index+1}. Reservation for : #{reservation.listing.name} | USD #{reservation.total_price}", reservation_path(reservation.id) %></li>
                    <%end%>
                    <%end%>
                    </ul>  
                </li>
                <% end %> 
                <!-- <li><a href="#contact">About Us</a></li> -->
<!--                 <li><div padding-top="10px" style="padding-top: 10px"><form id="searchForm" action="/search/?q=" method="get" ><input class="nice_search" type="text" name="q" placeholder="Search...">
                <button class="btn btn-default" type="submit"><i class="glyphicon glyphicon-search"></i></button></form></div></li>


<script type="text/javascript">
 $('#searchForm').submit(function(e){
   e.preventDefault();
   var search = $('.nice_search').val();
   var url = $(this).attr('action');
   //alert('search='+search+ ' url='+url);
   window.location.href = url+search;
});

</script> -->

              <li id="boomsearch"><div padding-top="9px" style="padding-top: 9px">
              <form id="searchForm" action="/search/?q=" method="get">
              <input type="search" placeholder="Search" name="q" >
              </form></div>
              </li>

              </ul>
              

          <ul id="boomshaka" class="nav navbar-nav navbar-right">
          <% if signed_in? %>
          <li>
          <% if current_user.profile.nil? %>
          <a class="navbar-brand">Welcome <%= current_user.email %>! </a>
          <% else %>
          <a class="navbar-brand">Welcome <%= current_user.profile.name %>! </a>
          <% end %>
          </li>
          <li>
          <% if current_user.profile != nil %>
          <%= image_tag current_user.profile.profile_pic.url(:thumb).to_s, class: "img-circle" %> 
          <% end %>
          </li>
          <li><p> ||  </p>  
          </li>
          <li>
          <li>
          <div padding-top="8px" style="padding-top: 8px"><%= button_to t(".sign_out"), sign_out_path, method: :delete, class: "btn btn-success" %></div>
          </li>
          <% else -%>
          <li>
          <a href="/sign_up">Don't Have An Account?</a>
          </li>
        
          <li>
          <div padding-top="8px" style="padding-top: 8px" class="navbar-right">
          <form method="get" action="/sign_up">
          <button class="btn btn-success" type="submit">Sign Up</button>
          </form>
          </div>
          </li>

          <% end -%>

          </ul>




             
<!--               <form class="navbar-form navbar-right">

            <div class="form-group">
              <input type="text" placeholder="Email" class="form-control">
            </div>
            <div class="form-group">
              <input type="password" placeholder="Password" class="form-control">
            </div>
            <button type="submit" class="btn btn-success">Sign in</button>
          </form>
 -->

          <!-- <div class="navbar-form navbar-right"> -->




            </div>
          </div>
        </nav>

<!--       </div>
    </div> -->




  <%= yield %>

<!--     <div id="header">
    <% if signed_in? -%>
      <%= button_to t(".sign_out"), sign_out_path, method: :delete %>
    <% else -%>
      <%= link_to t(".sign_in"), sign_in_path %>
    <% end -%>
  </div>

  <div id="flash">
    <% flash.each do |key, value| -%>
      <div id="flash_<%= key %>"><%=h value %></div>
    <% end %>
  </div> -->
    <!-- Latest compiled and minified JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS" crossorigin="anonymous"></script>
<script src="//ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
<script type='text/javascript' src="/app/assets/javascripts/application.js"></script>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>

<!-- BEGIN .footer -->
<div class="footer">

  
  <!-- BEGIN .row -->
  <div class="row">

    <!-- BEGIN .content -->
    <div class="content">

    <!-- BEGIN .footer-widgets -->
    <div class="footer-widgets">

      <div id="text-2" class="widget widget_text" style="
    text-align: center;"><div class="footer-widget"><h6>The Next Academy PairBnB Experience</h6>     
    </div></div>
    <!-- END .footer-widgets -->
    </div>

    </div>

  <!-- END .row -->
  </div>


  
  <!-- BEGIN .footer-information -->
  <div class="footer-information">

    <!-- BEGIN .footer-content -->
    <div class="footer-content">

      <div class="align-left">
        <p>Copyright &copy; 2016 &middot; All Rights Reserved &middot; Johnson Khoo Inc</p>
        <p><a href="http://www.johnsonkhoo.com/" target="_blank">Produced</a> by <a href="http://www.johnsonkhoo.com/" target="_blank">Johnson Khoo Inc</a> &middot; <a href="http://johnsonkhoo.com/" target="_blank" title="Amazing Hosting">Dragon Slayer Hosting</a> &middot; <a href="http://johnsonkhoo.com/">Special Thanks To</a> &middot; <a href="http://johnsonkhoo.com/"> Raz | Kevin | Next Academy </a></p>
      </div>

      <div class="align-right">


        
      </div>

    <!-- END .footer-content -->
    </div>

  <!-- END .footer-information -->
  </div>

<!-- END .footer -->
</div>
  </footer>
</body>
</html>